INSERT INTO Rooms (room_number, number_of_beds, room_size, room_quality)
VALUES ('101', 2, 'Medium', 'Standard'),
       ('102', 1, 'Small', 'Economy'),
       ('103', 3, 'Large', 'Suit'),
       ('104', 1, 'Small', 'Economy'),
       ('201', 2, 'Medium', 'Standard'),
       ('202', 1, 'Small', 'Economy'),
       ('203', 3, 'Large', 'Suit'),
       ('204', 1, 'Small', 'Economy'),
       ('301', 2, 'Medium', 'Standard'),
       ('302', 1, 'Small', 'Economy'),
       ('303', 3, 'Large', 'Suit'),
       ('304', 1, 'Small', 'Economy'),
       ('401', 2, 'Medium', 'Standard'),
       ('402', 1, 'Small', 'Economy'),
       ('403', 3, 'Large', 'Suit'),
       ('404', 1, 'Small', 'Economy');
